const HTTP_CODE_CREATED = 201;
const HTTP_CODE_BAD_REQUEST = 400;
const HTTP_CODE_UNAUTHORIZED = 401;
const HTTP_CODE_FORBIDDEN = 403;
const HTTP_CODE_NOT_FOUND = 404;
const HTTP_CODE_CONFLICT = 409;
const HTTP_CODE_INTERNAL_SERVER_ERROR = 500;

module.exports = {
  HTTP_CODE_CREATED,
  HTTP_CODE_BAD_REQUEST,
  HTTP_CODE_UNAUTHORIZED,
  HTTP_CODE_FORBIDDEN,
  HTTP_CODE_NOT_FOUND,
  HTTP_CODE_CONFLICT,
  HTTP_CODE_INTERNAL_SERVER_ERROR,
};
